/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:350b9d73-e116-4cde-96d2-68d54e1600e8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZXWgnDUPN",
    "aws_user_pools_web_client_id": "1uq8oq6rv1uopluv2um5tbsq8f",
    "oauth": {}
};


export default awsmobile;
